### ISSUE TITLE
Origin and long term plan

### ISSUE THREAD

**Issue by patwater** [argo-marketplace/CityGDP#1]
@vr00n what was the genesis of this repo and where do you see it going long term (if at all) out of curiosity?

**Comment by vr00n** [comment]
Thanks for nudging here. 

"Origin of the notion" was the [NRN California Report ](http://www.nationalresourcenetwork.org/en/Document/306226/Hidden_in_Plain_Sight_Why_Californias_Economically_Challenged_Cities_Matter) where we constructed a GDP metric using BEA's data that was only available for MSAs but is now available at a more granular scale to allow for more accurate local GDP numbers.

Doing like-like comparisons across local economies in the US is quite tedious and requires a lot of `extrapolation`. This dataset is somewhat foundational to unlock routinized economic monitoring outside of monitoring `number of jobs` from the BLS. 

Consider that while the number of jobs could increase in a local economy, the quality of that job may be pretty crappy. The GDP metric _may_ do a better job at capturing job quality.

Long term plan is to spend a weekend hashing it out. I will try and commit to weekend of 2/22 - 2/23

**Comment by vr00n** [comment]
http://bit.ly/bea_gdp_county
![image](https://user-images.githubusercontent.com/4397663/53706783-f6e71080-3df9-11e9-8d4f-54dc72f95b67.png)

**Comment by vr00n** [comment]
Also compared the current BEA county GDP values with the values I had calculated for the 2015 NRN report using the methodology of using job counts and they match closely :)

![image](https://user-images.githubusercontent.com/4397663/53706993-e4b9a200-3dfa-11e9-9783-0a0f924b3097.png)
